[package]
name = "chess-two"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["sync"] }
enum-map = "2.7.3"
strum = "0.26.1"
strum_macros = "0.26.1"
